# Generated by Django 2.2.3 on 2019-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='made_date',
        ),
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='made_date',
            field=models.DateField(null=True),
        ),
    ]
