# Generated by Django 2.2.3 on 2019-07-23 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20190709_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
