# Generated by Django 2.2.3 on 2019-07-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_manufacturer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
