# Generated by Django 2.2.4 on 2019-08-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_full_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
