# Generated by Django 2.2.3 on 2019-08-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20190810_1434'),
        ('product_app', '0005_auto_20190815_1423'),
    ]

    operations = [
    ]
