# Generated by Django 2.2.3 on 2019-08-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_merge_20190818_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expire_date',
            new_name='expiry_end',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='made_date',
            new_name='expiry_start',
        ),
    ]
