# Generated by Django 2.2.3 on 2019-10-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20190818_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, '보유'), (2, '삭제'), (3, '반품')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='status_edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='product_app.ProductInfo'),
        ),
    ]
