# Generated by Django 2.2.4 on 2019-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_auto_20191019_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='min_stock',
            field=models.IntegerField(default=3),
        ),
    ]
